#ENC[AES256_GCM,data:YGTnNTzV7ZpjEqI6/T445MCGBeUh/oI9S0Ms5rdhYAjSn3/59d4I3djy6R/uiGLBm/zi2M1NAyriuQJeUuI/Dsba3WumAwgAz03EM+mB,iv:ME768oEJ7UCXuVZF8zuWKM/B4tsnuqrXr5mGC+msSk0=,tag:MPdjPv9QbYq5ga2KFZ8ZAg==,type:comment]
#ENC[AES256_GCM,data:EVUiy4icnceLlRgljiFoW7eEObMXNfuZBmm7KZ94QeYTpDNecR7atX7YXoNaaPHJC1YVWbI0ulc6N0kv60OONX/6nY+a8LyCUhuwVSBiDA==,iv:9mz113lQ2h59Dzj4OG6WrlOJ+yGzjfdV2JTSJu6F4ng=,tag:a+626+myNBxsHgcaSZ0wcQ==,type:comment]
#ENC[AES256_GCM,data:ywI1pvW/3w1FTbXwPOp96c763yyC0uXULm20vvkh4OQRGpzIEl8lBKZPPBX0Nbikmlgq55jG9u7dlZzPKgiyOudXziBsNX8/8e4=,iv:xwv989Ih5AwltEv4pA9Ge3hxY9cLWXVOfl0prGqfJ5I=,tag:krdwjiEXEXIcZOfrqXQs0Q==,type:comment]
#ENC[AES256_GCM,data:O+SujRxjzOYCgfds8g36yaVEt9oeuGabZlNDH2cXj35BNHcJrx9qhmpAp9me4fs2Pn80h2r1lux29UK9hprnccxzYHXnhvaG3h7WJYZ2dQ==,iv:kkPmnzxVLq9tW3wPFXJJszXpcGrZCLMdHZVhbMU3+is=,tag:V13h8mkKTRKQqFvFXFH7bQ==,type:comment]
#ENC[AES256_GCM,data:dhS1/fEIPucWqVjU9WjzPS89xOSNwiUvs5vMaIUuKB/4P2ZFADRQe81zV9honBLovbzoKyRVrICpFOTp4S2h5goawegZJrOqGZcJtYA5Xg==,iv:4DL3TT3YccUDP4bdBa/YjZmfm67pVKmA7yILoi/55Xs=,tag:ohTTFRVCuCu7KVyhtThKeg==,type:comment]
#ENC[AES256_GCM,data:ak3gY7+hb62jcI8nPzeIurm2I8v1ndEyLWylOCvjD1DVvr9/ht4nsGHhtmzvfB7EfwcmD5rR8NJXlw==,iv:RfEHOxE8iE1xJKdPF1O0NIfau6L8Q7itNobWh9DgnbI=,tag:qc6zfAtEVgsycefN32b04A==,type:comment]
#ENC[AES256_GCM,data:W9LmMtFgmPAyj6KUfes=,iv:ViI5rXRtWUdckp/k+PFMk1HBTUzkCa+G5id7+aW/THI=,tag:W9efvtE6uUy9gEjLk8r+0g==,type:comment]
#ENC[AES256_GCM,data:K/V6ix3fCH5Mfg==,iv:TWJ0LrlOCi0ZxIp/4z1OgVS3f2SJKuxXtQaC1tiiMZM=,tag:xkl0M2QZYqeqsLkN+aG2WQ==,type:comment]
#ENC[AES256_GCM,data:yAbY3tmvLGaYwLf9,iv:9dP13VIklMOJ/arIgEeKsSiuyD8HpPGQpN41VroKkDs=,tag:61D379rRu5t21QsasrV3SA==,type:comment]
#ENC[AES256_GCM,data:tDeh524wGitcWSlSE2dFi9w7CPPfOl/Ri++sl+f8SEG4z6F+NnBL4ffq5H2PX9mf0JmUn+45VC7tcl6uaqepocFuI6KJba64pR4E,iv:zYB7Sxs4Ig7K+p/57SXByuTH2sytJctP3jjWxB0kT8o=,tag:nQqzf34UCCXvNTKfOKIZ/A==,type:comment]
grafana:
    adminPassword: ENC[AES256_GCM,data:wLwrXhrRzAMu1guce62GiAerYZGdSJfc1ERIdMthQTbc26nZ,iv:XRLNOotH0SkwDvYPjk/ofdGgX528z4HzIunMqOPxe6o=,tag:lAj4A+X/BoV1+xTDYsVCbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY2ZUUGpLODJWSmpBcDdD
            dVNWQVhjQzh3Q05hYXoxSU5Pb01ieTg5eEUwCmtDTGxtUWN3S3daNGdzeFBXYjFt
            TWhNaHpmM214UUk5U0ljdnN1NTQ5bGsKLS0tIEcvQ3VTcjl4SkhHRTNhVm1RdnRu
            dXA5NjVOcW9tdFhPMFJibERZTzh5SGMK3XidIJSTzl+UXzZ7GROFTysmHAGxx7aA
            d2L1fVTbOZGsMEPWRgh8nQzeK7W5WG7LRCsvh1O2yCKkAKa9mVHzpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
    lastmodified: "2026-08-16T01:30:01Z"
    mac: ENC[AES256_GCM,data:LOrMYPXGpMgWM+ibZNrXWy+g3K4/1oiIJyJYp4q68XM/3GOCgM/LITmmuzD7Qe3GZDd+xzAFTBb2XmJMm6L7iZsJng9kQryf/u8P+tRcEAHiMIkWEOH4FJjM1ylLhb8u0mfbTeZhBzHj9lpRFjF+WV3TxWy51VKXsCvlfO2uJIk=,iv:8phGo4CPHXVCuHFdqm56H6164pV/tWJ33kY1Afxy/fI=,tag:fWXM6TFGTZymo9nWRnNeVA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
