grafana:
    adminPassword: ENC[AES256_GCM,data:7nD7j+KFeRq7POqGBai+Fxzhu3m5C3HJDpVTJyx4Bqru/bzu,iv:jFfbOXvSE/xDUqy55w9xa6dSdu6uNrTqATa8G5Qm+Ag=,tag:EVEzGPqBJNsRAmdcy/5bZA==,type:str]
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbG5paDBZVktDRiszMGEw
            V2NldjZnVWl0QkljTGlrWVdIdElnOERUSkhnCnQ3Z2pUbzVkeWxVaXp3ZVJ5ek5v
            ZlJjOVBjc2VCeXAyUGZuNWJodlNNV3cKLS0tIGZzTlZFMTRPNG9Xc2o1c1FDc3N0
            cG90UHBvRi9zMFMyenYwaGw2L0o3RUEKH9liyHuqiwrkt38fmVUnQ8a/aTDTyylN
            NyG1UU/4NiA5cXonpjG5xYWf7zCYY4u+nUrilUUWeT4theE9sUjnDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T04:11:30Z"
    mac: ENC[AES256_GCM,data:2LPWHjAZKnsjaRT5BRqr37RxUPs3Gmc2mbP9NiSe37xF2+TleLQ/cxEW5nvixwudOJquLyT/ogBZNX0kjb6kg6BUG+S9SSz6QZ8aw2llyTFcihoXeXipETEyDXuXtPLamUA+eLlwSa/8L6iJtalrTbkz1hA0miPiw1zf4juYP2w=,iv:FGIUlhpvO9Qm73EKBN/coTEqV5gAuL9JFXFtM6YAxUg=,tag:vJ9lfhVSl8assFvFqQNiwg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
