sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbG5paDBZVktDRiszMGEw
            V2NldjZnVWl0QkljTGlrWVdIdElnOERUSkhnCnQ3Z2pUbzVkeWxVaXp3ZVJ5ek5v
            ZlJjOVBjc2VCeXAyUGZuNWJodlNNV3cKLS0tIGZzTlZFMTRPNG9Xc2o1c1FDc3N0
            cG90UHBvRi9zMFMyenYwaGw2L0o3RUEKH9liyHuqiwrkt38fmVUnQ8a/aTDTyylN
            NyG1UU/4NiA5cXonpjG5xYWf7zCYY4u+nUrilUUWeT4theE9sUjnDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T03:36:01Z"
    mac: ENC[AES256_GCM,data:0zJT9jP4eZVy0OPHErIhkX2QMy7dvydEgU25PyW3Sf/DKfxuYySp34Rtv0FGPiiVrEl+hGx5HkVxQqtLqcHJeI5rJOvgQGSP73wjjHvW1oTfZERNNcp9OrCNDCQgiE8nPHCQPgttgRE1+ApoT+KKieadiclSAoVO6dVMnQNQESE=,iv:kPrqyVhYQ0kNFj5zADpA9HeVvqBEINOaVy04E50fCjI=,tag:ezmFlJnZR0+dm4cqiLePeg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
