apiVersion: v1
data:
    users: ENC[AES256_GCM,data:VjA9qxd4623flVB5q0Iojy9phLISeSSd5s3vpAHyiMrCzfI2EPJL45d6W8pYtF6Go2jgyIprIA684KfWkjpzcL7qT2QtTqqu9wRZpM3AtG7Y6+xn8EwSmopD6xU=,iv:3C63ONw0rGNArm6OUit2Y9OgotK42Xu+/doMhttx0kw=,tag:ov3J5ed56pqyXEb0L6lxwg==,type:str]
kind: Secret
metadata:
    name: basic-auth
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFM250TFEyMUQzTCtKYllR
            dWN0M2xxL3FvUVdnY2M2MEZNbUF5b1VweUVBCmJGMllDd3RtT1BOMmoyRlV5bnRJ
            cUJiRmJ1cUpwejdxVndVdUFWaGQ3MG8KLS0tIHhlY25wME9sTklVOExCd0FUZFZT
            Q01pSEpUNU5tQW5MckZVQVpldHRaaFEK7qoB0My5422tcSK1UnSlzVDgUXgYAdr+
            ccAHcBjAqeCwBhcYuafL4hDkusMDuljX4NygRDc/yJow0AACRZEdTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T21:22:05Z"
    mac: ENC[AES256_GCM,data:OLtbPhs3lt0TxOTuojThsjXAnh9mMVKWBP/xGPf2guD2pwRnF/zPl+MKg3Xkd+EiO62zL0vQOroxlLplhrE+BjjrRa6GJqp4R4657uX3N5f/hNq0i9tlnMwZWi8lp2XAFS/6jmVBs7mfZZEyoAc5txoOQpr5d1rbD+xeE11H5sY=,iv:3H7pj6ZAK+YvVZUtaMl2EkUx1P/8JuqnBGKOhIh3ccw=,tag:qAJjU62N00iTPp3qJ3CwVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
