# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radicale
spec:
  interval: 10m
  timeout: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: radicale-values
    - kind: Secret
      name: radicale-secrets
  chartRef:
    kind: OCIRepository
    name: devopscoop-app
