apiVersion: v1
data:
    users: ENC[AES256_GCM,data:WkvQpujOqA+zcfYdKAdSw2eVwdbUNDy/LrR4y758H3NqQU2gGaRfKGSR7e17Zzo/U5rmG4KP/f9QJSPtNbUdWGr1lep4QQ/VCejree2x097/XK8wcyOG/F7VIvY=,iv:B8pqvxysfoc8jJdB/UqoBcRBoFHkYE5AmTCuORDbyaU=,tag:TyvOtyX6gcXDDdDU1PaKBw==,type:str]
kind: Secret
metadata:
    name: users
    namespace: radicale
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWM3owRkVkT1p2bWViU2dk
            WFZoV3NROWNjeUZPVGgydjNFaEQxMWlIQ1dBCkNROHdkd3JranBtRldBc1BBQ2d0
            TjYxdWFxUEQxY2lxVlFUdkV5TTA3UEEKLS0tIG45dStBc0xIR1lBODFjMVFQdU1D
            Z1N0Q1dTUnBqYjBZNHBwckdCUXc4M2cKEaiDj2igK1W/0RjWAxrwlitySKgDVtzj
            zypsuL7BAWI0gDzrBzhVEMpGUqK4z1ZVJrwefToEt6jS7LdjnKoxCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T21:40:45Z"
    mac: ENC[AES256_GCM,data:U4xjFVErqk5vt3Fhs4aVfKmDUd7x0LGgq15CJ8qVwgBAceqoh/vL9jf5wjFwEY77gtsnuMMYCdV3CyhkpupPo2Anzma8sHvzeKAD29y26WENfXv4a7PYVsVu32agZCl+flYi7/IYQFZG3kQNRoGpe0H2chN88ifKhGiu7p4pIA0=,iv:9P9E8Y3tJM9h/oUCpPP/yKdSiPPSlO36B3pZsCHO7RM=,tag:BZUJHP139/5VVPlfoXgW3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
