apiVersion: v1
data:
    users: ENC[AES256_GCM,data:bRiRTdhjDvg48l7/EH5aMtqRrOf8wKyrh8I5AEkDUkKTq1ZZtwHwXiBgILNyQwQRURaSgtd07tRYxX3+98b6fhtL93TNFo1r11R1gdnhFgJ7ddtk8bYfc/+5aXE=,iv:woOOHBnCz1PV/qHUyvo0CoiRfHghFNWbjnqnPEXNQc0=,tag:lBEt7F+xuRVRbichZthYDw==,type:str]
kind: Secret
metadata:
    name: users
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QUdkSysyV21ReEJ2S2Jk
            RGI3NjRENUlUMkVIL000VVVLSGJBNGVyTUM0ClRrWlhsMlN4QWQxemRxRXdVWm5G
            TGpTYjlxYTdVQWQ1Y3ZDN01HMU0zeFkKLS0tIEg0MTN3d1NkcjdpMHBxWENuT1lN
            b3RtY3ArWUdrL0xuZnBXMGNQclBuNmcKJhujM7AYRSPIA2kkGbY34GpE0s/gz7r5
            Fd5J6ImJxGb8rxu3bOEurDX6N6YEZWgUaVhuqqgcIZR4OADwnolkBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T02:07:12Z"
    mac: ENC[AES256_GCM,data:rXGu50eezPBMHjMPFAaul1ziIG3Mw+8nvVCFEEDXeYbxYeM0ciioWRcb8dAS1QfGxnFe1pOV0Kmqvl3ffhqkut2jBhCxCUI592wfenwq4KTMrZdmotKRmnZdvefGbna/Mv8wXgbOl9ewftFLYB/8abDU93olhXZlNgP4bQI4nzY=,iv:hDc/FgKeOw5MfkTYJgXOZFqNFK6tutHsme9ZvPd1H6Q=,tag:kAxx29jw9hopuZx0rpnjvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
