# dyff between <(yq . <(helm show values metallb/metallb --version v0.16.1)) <(yq eval '. * load("values.yaml")' <(helm show values metallb/metallb --version v0.16.1))
# vim -O <(helm show values metallb/metallb --version v0.16.1) values.yaml
