# dyff between <(yq . <(helm show values cnpg/cloudnative-pg --version 0.29.0)) <(yq eval '. * load("values.yaml")' <(helm show values cnpg/cloudnative-pg --version 0.29.0))
# vim -O <(helm show values cnpg/cloudnative-pg --version 0.29.0) values.yaml

resources:
  limits:
    memory: 129Mi
  requests:
    cpu: 10m
    memory: 129Mi

monitoring:
  grafanaDashboard:
    create: true
