apiVersion: v1
data:
    .htpasswd: ENC[AES256_GCM,data:fb2LZU7EybZHz17iaZS0KraNMx4+H5ix5NcSMJHUI2nJbSWgw3vBAOXYKyTNvGQqZGKeug==,iv:nXxl3wkzgiJzh59BpQ6P6wdcz8SMvLMcLkQIiZQgHkw=,tag:NYrP3TojIFGmZ6yEg+TrDw==,type:str]
kind: Secret
metadata:
    name: basic-auth
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRzFaVk95YkUzbWNURGFj
            OGtmcDlZWDhqRWppUWlnSVl0NVRWVFI0VXdrCkVueUZBdVNkU041UzAzQ1dDU2hG
            K3FuSysyQzNGUnVtUXQ5clg1SXhnWXMKLS0tIDJzZncwTlVaZktQNm9lbm1hemFK
            d2sxUzBQRlFXT3RCOGMyKy9CWW5VanMKAdDq3XUAS4ond5UNBHbMibaiaBjYGnnA
            rxv0fCpOXZvbLPO0n7jDJomrvlaewd2m9TmzYIG9JN+WnuzescLv/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T19:31:16Z"
    mac: ENC[AES256_GCM,data:BiT/YV4Xjs700BV0iOFTtCJ7CUB5PrBGdDGBKvjr1/aZNXC79TI/FirC6lqPJRKgfbmqKXBBRc0KECWgM+J0WE8r0+rYLlGYor+QZRBYIJKcJw3Xj4sf+urNuIE7bUA6z9BJY9KnmhKwbE5AxgyrBJdxRoWcAvt8/rIIq7q89Ng=,iv:YfS8ifY1DoccV8rEqyCwROrzUxYEOTNgynxfUIue+qA=,tag:si9yRMxZp89u36XCji96XQ==,type:str]
    version: 3.13.1
