apiVersion: v1
data:
    .htpasswd: ENC[AES256_GCM,data:nWWa/HsJ3QL2FtoltYWDMdI/4G5f4n1xFZzJE0cVzSRFIZfN065OLeQClckSIuvTOHI3CePypFNxO11s7uWcVlQFUVeP9KObavpNn9VpKBl/wOs1AMVZfg==,iv:gh6KHljHZydZwI0SUNnyke0Zeqor1FQ8DY5ktHadgeg=,tag:YubbE+t8+pQ71hMtcOH1qw==,type:str]
kind: Secret
metadata:
    name: basic-auth
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteEJueTV5RVM5YVNtVU0r
            RmR0ZTQ2cysvS2pOUkNpWVE5OXRjQm91WG5BCmJmcXFjdmZkMFBsaE91OFk4VVh1
            YXA3R2dtQXA0WFQ3ZFFpS2pRbE1mRDQKLS0tIGU5d2FTZzZCaTZUcEtvVFlIVmZ2
            WUFXWVVFVG1Ra29XbGN3ZTNqem5kc00KpTZTf3yqV6PNUXn9no4Tkm73q87lw0sF
            mc7SReABBK9pbIIphd1dhm5XGNeq8VIq0myvVGIXUt7g1qQzeXLbqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T18:27:14Z"
    mac: ENC[AES256_GCM,data:hAgef4a3Y5zAEdvZI9qz4bJtOMv/UNwE98P86oLkLUL/kVCsOm+c8sbbDYa/lxkPSaNrVrad6wvlTLMAbd7ToQvqpssixQHemwZ00S4IxnfvWQhg2Rl5B7RUr2cso5jFvOTnYetiPnRKHr1Cc1L17LCM8TuDDb+RGoRViTjhS3g=,iv:1ZQS4Izxp9KxopOI/LwISjcEvyKmOaoj1QY1axYM33s=,tag:yz3xb5QKocw6cB5DOVptdg==,type:str]
    version: 3.13.1
