# https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize
# https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-secret-generated-with-kustomize-and-sops

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chorechart

resources:
  - namespace.yaml
  - cloudnative-pg.yaml
  - ocirepo.yaml
  - release.yaml
  - auth.secrets.yaml
  - chorechart-auth-policy.yaml
configMapGenerator:
  - name: chorechart-values
    files:
      - values.yaml=values.yaml
secretGenerator:
  - name: chorechart-secrets
    files:
      - values.yaml=helm_secrets.yaml
configurations:
  - kustomizeconfig.yaml
