# https://metallb.io/configuration/#defining-the-ips-to-assign-to-the-load-balancer-services
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
spec:
  addresses:
  - 192.168.8.10-192.168.8.19
  # TODO: Add IPv6 addresses.
