apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:5eogMc/dRg2nxz6JRQd2ngEChcfBPGZk13l2ZzMWzGeSWLYE,iv:7iCjQh9jtG6fJ1mR1pKqAq06iwNDHwJATN8m5q3vl0U=,tag:yML8JZA++pOMSQl4Z2vqPg==,type:str]
    username: ENC[AES256_GCM,data:t5AVlFZpykQ=,iv:Zs14Ez+GsCEyNg9QWMEAqSZI4ctjTgw/cu3KW/R4u58=,tag:9WSDKOOfEHDH4PBvog9gUQ==,type:str]
kind: Secret
metadata:
    name: oxicloud-db
type: Opaque
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbjIyNjRxbTlFVjNpQXJV
            eHFMQ052YWpaYU1YMWEwMXRsWTlxekIwK2xNCmZIZG1zR2UzNVFmc2ZidHlna0gw
            ME9sdWZIQ0FFdnJHSUkrNjBOQXNSYjQKLS0tIHh2TmdIWVpHWVJ3R0U1RWl3VFNs
            WTFKMUI0YU05Q2k3cFVQZG9tNEMzUVkKFqLhNOTkqdHl8sB7lLt025qdYq8yB3Gm
            2841aqLYq/NuelEflppTAEVxTK6gb7ZZwyqFDrPB4VMq01xqG0AQ6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T00:41:10Z"
    mac: ENC[AES256_GCM,data:f0ZW3/dwa/p3F0UW1Q/tywKzOYRWuM+oOAHnHrJV02h/8FTgtVALAdPJw3TTq0s6gq4T9ClzKa4qwpTfWE0tPasMm2SeZGbrxjqulEnA+bUVYnU+TfsL0YGTODOqEYfkhQM1R5/jO3R89aH4xSn7P217X3PSMbM2j2ljQyuKplg=,iv:6lmszjDGL1nm1XZIOFu36APG2NWN/xXqQi9DlKeJ3sc=,tag:lSAxgBSERmNOa+b2lUPndA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
