# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oxicloud
spec:
  interval: 10m
  timeout: 30m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: oxicloud-values
    - kind: Secret
      name: oxicloud-secrets
  chartRef:
    kind: OCIRepository
    name: devopscoop-app
