apiVersion: v1
data:
    .htpasswd: ENC[AES256_GCM,data:tvcgFgJMY2UdqoFUagG7HrgdJ8LV/4c9k3pnubCHIcDLut1vy/VxmSXjR5RdiLVgTKtIMw==,iv:ks0QMHFquVWjjUyzPQr0moSZjx2ZVJbaHBh703f+nj0=,tag:q0oAw8ptW89TQxFYN5JD6w==,type:str]
kind: Secret
metadata:
    name: basic-auth
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbks1UTNmNTRoNXZYait5
            OUdsVlJiVHJwdmlEYkFRYW1FRHBTWjdldUVjCmFHLzczdXRsRGRRdnFMZ1dsSDM2
            WXJ6bW5VTGVWRlFHZFcxYUF4VzVybDAKLS0tIFZ5NGp0aHhKSnd5c2R3RHBLSmxC
            S2FBUW9tOFZqNjlueGRnVG5zT0tLTlEKcSlTQ4TKBps0NreoF1wIm+dfTEWSPpJZ
            LOnUnwNRHuZ7owbn9uMtX/74Os84o315tH5QnW0Hj+4KSzwiCFkibw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T05:23:10Z"
    mac: ENC[AES256_GCM,data:bM87SM9PFyWbR4e8qrP9n2gN6lB4AQ9cZEbXsyruVfzwPguWOIyQe04MkK9nGJp87RXvh5dEGCQI/CnfkQU9ckh0f+Q8GhSb9J8AMTRJFiJ8VTBtTpq2wb7N+exXMuBVIMDncRgDrxC+EeSQ75AhnUKKbtKpeTiFTxqmOFQuqP8=,iv:V9WLoWPpzwcQWoUmHtTFEbwmwovy6pQi1biXq6i9QeY=,tag:M4V+i0j+lphKMhT5LxV8Rg==,type:str]
    version: 3.13.1
