apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:PZP3PigbC4DJbZXhKf6Cc4xWP0dhO0gLxO1uamcmbyicjNBddyzFswndE1QGHXR1UPcwkpa2wup7lSCGVzyMzOYcx8XkrZqZJ26e/frPO3U=,iv:AulgeQLcTUULjaff4U8grU5rlPtTWBCz/XD7iv8SljQ=,tag:fI5Y5MRoeafGhYn9OeALeA==,type:str]
kind: Secret
metadata:
    name: basic-auth
type: Opaque
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWVlvY3FMdjliZkJjaGgx
            NFhYM3p2dEQxMTQ4Vk8xc0JPdU1RY3diekN3CkRPSlBTZ0NUdEgzZzZRWUlyOHl5
            WU9kT1pKb1ZwTmgzamU5ck9UMGo4YmsKLS0tIEZZbCtBTDJjUHRObmVmei9PUlpS
            ZXBZS3RXR3FVb04wSkNUZnhqaDNxdlEKSRaayE3eqbnVLmXlSdNxN7+gCCs63+CC
            JwNb3u+yR7KX4Ktkgesaberi3YvnbyMqWlHJp0/Fwghv9kilNt+8Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T03:53:18Z"
    mac: ENC[AES256_GCM,data:4lX36QEo6z9UkFbADWIgqlfZjqmWNy2ZhZhVlEdxQokDO32uwLpv0r+9hr5SwQI/sOFEMDK4+XAims9wMbd7UTrihq5SkR/Kmif57L3ukg17PufbMz61mPii+zwt666VHLwmoGCmga+w1xSyXu4X4YtPQrofMK2LzvCZ9ZgA2lA=,iv:LpV2rYVnmuvwUylf7O/9VUI+exOsuwOyvwU0iVtCaGw=,tag:QhouQ+xHtSz9ehZ3Nyl3kQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
