apiVersion: v1
data:
    .htpasswd: ENC[AES256_GCM,data:poRP3NLzsLe02gJrRel5voCGpLevSVOZUpoVlW+5b2sc1IGvEarko2dV+4sDW9pW3/jxo8vZN1At7dd8,iv:V5KyYoFRM/1S/GgrbtTiow2qhSLh2pUvUdXZu37UeOk=,tag:LY3aQMz1CccWUH6O657f/w==,type:str]
kind: Secret
metadata:
    name: basic-auth
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbk5HbFJFRDZkRXpwaTgv
            bktLUXM3N1FnU3ZZYlVObW01QzNsZG91NlJFCnBkdHdIczJGMytuaHZueVliZFpL
            VGZSTGhsdWIvM1AwUGlZdmhWOW9QcDgKLS0tIHVwMVpyUGZCbkZEdmJRRVVRalJL
            anlZUFZ2T0E4Q29pYkZSeHkzZnR3ZFEK/YiTfIkUxJDN3v8ZGULcYnFqGASmCg43
            eicigZ33SICQgXWHyMH6XFUv6aye5lC1ysWb5PBCUFBGy1lPV5AUAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T04:59:49Z"
    mac: ENC[AES256_GCM,data:XKkKW4Zrn+l+xOxeK8o0E3RfA6tepbuNHrotF7uBLNaJE2gbwvUdGvNqSrenJ9CjR5qyDwS5iGshbG0S2+NCSU6a5l5eoyp5STpIjTqY/kdj7tpPzXSUHO2ZhdJZXs5zTx95abPyzFG+G1GB/COb3xZR8RCLhqSeb01AWHgHmtI=,iv:sPTxyLKZH43J9sZSiqDTquNpPX2czwkehNGkcweeRG4=,tag:yekEhE0sWqJuJQ+4Cs4Wxg==,type:str]
    version: 3.13.1
