apiVersion: v1
kind: Secret
metadata:
    name: wasabisys.com
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ciTOuIf7STRC5vQYMV9yngVxy94=,iv:+J1+oIhiymmXAsC2Gff3ELvvbv4y64cm1lkaJ70wOyI=,tag:uKk+fzXTonzz8gNPk1LT9A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:YVu/wJ7DbpelrOpohnDQfd8NfMCP0PpGjUeDIvOFha9XPjx8bPcQTg==,iv:c89bpoaDXSkLs6rVonRpuMPj7NHr/oPYzr77yI2GKRM=,tag:mjhhS9Nv1+Uljf8aentUCg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:lJfWdtA5bOMAfj/QxQqNW9S6JX1TL7wsD+GPV+cQa2bJLA==,iv:GbuU4QJsoj/YIbDIUcVIE7FEGJHlYdO9lWn1AX/5iWA=,tag:tDCyGAMezYOvWYjme7gQqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cXREZVYrUVVmK05RL3BJ
            eHVZRDVXaDdLQk1nTVJKWWdvTjROSjdPbGhRCjhSUHFZT28wUmV3QUkrZVhQUUV6
            VG13L0V2b3hCNVlhLzZzYTEzbTNIaTQKLS0tIHIxK1h3YUkySGxsSDFlbWQzZFNp
            U1YvTXA3c3JhZndOdnpMaDU0YnI2UUEK5p8wkBlt9cZg5pL6Fu8Y79CkmlWSqCPg
            tQF+ozNSIsem7y8K7EYrvPgO6z5fdiWT15jPcB+P/sLkUYOS494C0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T17:18:38Z"
    mac: ENC[AES256_GCM,data:Ni+ckDHOOh0vcTTzIIHeE+fABO0bhnaCNemerCDKE0IK2Pte3Ee/8mdcveqvNCqI/rMVTRyt+TogEdjw+7wIGc/ugyEreNwIL3dTp/rfesWbY0JuOeQFeO2+Kp20oXE6V2QGwaYv+COg1jsfFBobmaVa4M1MTEmpOjhcO3ewukg=,iv:ADDooSqSFnbsmJnQ3qaK2JT6Ah2dofw6GVdCbhr9nWo=,tag:kDNTqKbdHnUSMt+IiSgBgQ==,type:str]
    version: 3.13.1
