apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud
spec:
  backup:
    volumeSnapshot:
      className: longhorn-crypto-global-dangerous
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
      secret:
        name: nextcloud-db-user
  instances: 3
  monitoring:
    customQueriesConfigMap:
      - name: cnpg-prometheus-apiserver
        includeRaw: false
  postgresql:
    parameters:
      checkpoint_completion_target: "0.9"
      default_statistics_target: "100"
      effective_cache_size: "1GB"
      effective_io_concurrency: "200"
      maintenance_work_mem: "64MB"
      max_connections: "200"
      max_wal_size: "4GB"
      min_wal_size: "1GB"
      random_page_cost: "1.1"
      shared_buffers: "256MB"
      wal_buffers: "16MB"
      work_mem: "4MB"
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: "100m"
      memory: 512Mi
  storage:
    size: 10Gi
    storageClass: longhorn-crypto-global-dangerous
