apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:Xw8K0nJDBCqeg/WDaQDZfaqD2dfHsqmw7tDkQQYjyvNEyQ8+,iv:PUKd+hRyPh/2JrTa5lOo6oLfTDBQ0cuXZXL05BgXzNA=,tag:lrtgZflkkzPPt3//6AkREg==,type:str]
    username: ENC[AES256_GCM,data:DhPrJz9BDKhz,iv:nmPWkVHVHIgvruHoHaRtsKcOFAOkUZ55Z8GePi2x3RE=,tag:SfKrnA2yCXO1gDLl9+JjUw==,type:str]
kind: Secret
metadata:
    name: db-user
type: Opaque
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QmZoNklqeE1TS2ZQRmk4
            NjlWVFJZdnFTODJzZDFFR2UvQTJtU3dYblFBClVsSjRpRjJZYnl2cEFHUDlxQ2xT
            TEEzemczMGVRSlNHekl6M2M2WDdYbWsKLS0tICtZbXpsSzdRdUExZVVOTnkyK2RN
            L1BtNjZYcDlTbDExZ0xWcDk4Y1FoVkkKF1smVF6qesrtu4YUuFKmI/1LUN6ukOOY
            UtCEu5UwLfOcaMETfNZmlzBwpzXYp7cT97jyHbNapSn0TsVJe7+QVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T00:15:15Z"
    mac: ENC[AES256_GCM,data:XirzE4rTnnEejJkHLZEES/CeRcAOCXFUMf6hBu0jYNuxAFySbB9bNz+JpBafhgG3ttFynUcu0iKQxAhi1QSL35jgBfvCM5XvSrq4MsuKgrZ34NaCEKL578oDgFcG59RLymqZnAIjfnJEE9ipMJQ0r1f2kplaOjXZ/jeZuNhZuV0=,iv:PbvR6/XuFpdiw7nWKSd9uBduYpXOYC1+JTYZI9F0jaM=,tag:RaHEHID3wfVWpXa9spPJiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
