apiVersion: v1
stringData:
    db-password: ENC[AES256_GCM,data:tkh24R/GkbmAwCvKENcf9fpszqhgX/UVTxvVCodGy7Dt6yhH,iv:UwEAwCGL9MFLFX7YmmO0ColR//CUtnfZLB9vZ0Vn7jg=,tag:pcFcwJ0EhxDSI9mQEawkvQ==,type:str]
    db-username: ENC[AES256_GCM,data:2GH7s+0MYRmt,iv:DLqQiKZyCDQCa+X7oCPn+FzkUX/sJ7Z3+wlws2zES4k=,tag:z+vmwW7RFt8et91R8XjNyg==,type:str]
kind: Secret
metadata:
    name: db-user
type: Opaque
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QmZoNklqeE1TS2ZQRmk4
            NjlWVFJZdnFTODJzZDFFR2UvQTJtU3dYblFBClVsSjRpRjJZYnl2cEFHUDlxQ2xT
            TEEzemczMGVRSlNHekl6M2M2WDdYbWsKLS0tICtZbXpsSzdRdUExZVVOTnkyK2RN
            L1BtNjZYcDlTbDExZ0xWcDk4Y1FoVkkKF1smVF6qesrtu4YUuFKmI/1LUN6ukOOY
            UtCEu5UwLfOcaMETfNZmlzBwpzXYp7cT97jyHbNapSn0TsVJe7+QVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T23:32:12Z"
    mac: ENC[AES256_GCM,data:Mkf+nyiYptJ2UqkWjK8J+kkmSltqxnChkSSMU5oztqXDefUKL+Wgvzm/Qa4r7ojwWLl8Hc5Ca3geFCXaBgqUxEFsFG6+JrgcvjybF4ptoMmvZI6FLUVncPmDftjtGQwArJvQAD1cHui58fZuerfAxr7NeQPq73RWy0KEWY90nvQ=,iv:Amu4QF24lfI3xbKDJYNVDsrDhMCNr+i0AFHvLe3tKG8=,tag:bzdDbHq7Mw2lfe5OwaTobw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
