apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:xcakxy9uy2yY2hXmmi+5LBQuK28b1jxkaj3WaktXCTX0tseW,iv:OenLGA3ubvRQHM2Ax0Avrz4QHHPm5lQquyb7tB41jWo=,tag:Zf03llzyF3riPtfN5L8Eaw==,type:str]
    username: ENC[AES256_GCM,data:wnMOoh9TrQRW,iv:jp/m4+yIf68Sw3ZK1B9Gzm7wiWv/4l9Omdgrhv3Iqsc=,tag:3KNks+wI/A4FiZVT7AWFxA==,type:str]
kind: Secret
metadata:
    name: nextcloud-db-user
type: Opaque
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QmZoNklqeE1TS2ZQRmk4
            NjlWVFJZdnFTODJzZDFFR2UvQTJtU3dYblFBClVsSjRpRjJZYnl2cEFHUDlxQ2xT
            TEEzemczMGVRSlNHekl6M2M2WDdYbWsKLS0tICtZbXpsSzdRdUExZVVOTnkyK2RN
            L1BtNjZYcDlTbDExZ0xWcDk4Y1FoVkkKF1smVF6qesrtu4YUuFKmI/1LUN6ukOOY
            UtCEu5UwLfOcaMETfNZmlzBwpzXYp7cT97jyHbNapSn0TsVJe7+QVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T22:45:03Z"
    mac: ENC[AES256_GCM,data:VdT3fNltw0c6xP4cSQV51aoRdFBiOOAFYpdq/VRT5xlvQAl4eS/HFv6hYN+Sfh9p8+znq5XkIXdErqbEHCuZZw7Nn6hiwrGZTwSrnI9bTa0Vusxsj1ua7jMs1tZ5rZlDAh0HmOfilKuOMHcVr+w9J7K9AatcSGfq3DdVTkmzrCo=,iv:5aEPu0uBEuwk/pp3TvW8RlOGmUv2YLpQUAFK56Lr99I=,tag:619xAXQqF/+50kIKVU86ZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
