# Show differences between this file and default values:
# dyff between <(yq . <(helm show values nextcloud/nextcloud --version 8.9.0)) <(yq eval '. * load("values.yaml")' <(helm show values nextcloud/nextcloud --version 8.9.0))
# vim -d <(yq . <(helm show values nextcloud/nextcloud --version 8.9.0)) values.yaml

replicaCount: 1

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/server-snippet: |-
      server_tokens off;
      proxy_hide_header X-Powered-By;
      rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
      rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
      rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
      rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
      location = /.well-known/carddav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /.well-known/caldav {
        return 301 $scheme://$host/remote.php/dav;
      }
      location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
      }
      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
      }
      location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
        deny all;
      }
  tls:
    - secretName: nextcloud-tls
      hosts:
        - nextcloud.6j0.org
nextcloud:
  host: nextcloud.6j0.org
  objectStore:
    s3:
      enabled: true
      accessKey: "GKe214ad1a729b32f06ba08766"
      host: "garage.garage.svc.cluster.local"
      ssl: false
      port: "3900"
      region: "garage"
      bucket: "nextcloud"
      # Have to use path style or we get errors like (note DNS style bucket prefix):
      # Creation of bucket "nextcloud" failed. Error executing "CreateBucket" on "http://nextcloud.garage.garage.svc.cluster.local:3900/"
      usePathStyle: true
      # The Longhorn PVCs are already encrypted, so we're opting to skip encryption here.

internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  ## Database host. You can optionally include a colon delimited port like "myhost:1234"
  host: "db-rw.nextcloud.svc.cluster.local"
  existingSecret:
    enabled: true
    secretName: db-user
    # TODO: Getting this error in `kubectl get events` if I don't specify usernameKey:
    # spec.containers{initdb}: Error: couldn't find key username in Secret nextcloud/db-user
    # I should probably file a bug for this.
    usernameKey: username
    passwordKey: password
persistence:
  enabled: true
  storageClass: "longhorn-crypto-global"
  size: 8Gi
redis:
  enabled: false

externalRedis:
  enabled: true
  host: "valkey-nextcloud"
  port: "6379"
  existingSecret:
    enabled: true
    secretName: valkey-nextcloud-auth
    passwordKey: default-password
