apiVersion: v1
kind: Secret
metadata:
    name: peertube-admin
type: Opaque
stringData:
    #ENC[AES256_GCM,data:8sUtThrJ7fD6gUW+6ic4mL0XWu4J2r01ehQis93EKck4BQ4RagN6bWFswucOOh0T0cvP9AS0yTNfUxz6o6WkccTCalg+ynUgmnYL0ZE=,iv:wRir3lavQY32bx/tqReqWSeWoEGcQqWtttqc1B0o0Ok=,tag:+ThvOG3N9PzdlR5VVZ5ixQ==,type:comment]
    #ENC[AES256_GCM,data:MkA3BMIBp/yXw3Sd3QljkXaKuTE5YqOXN0Ck3a5xGxafYic/O/FnSlXVYzI64NmRsCwxoT79QwI17uSIEMdXm5mL6lp8sRBLz0XLOCZX,iv:47O8QVf/sm1B0qBEjUjKStuAVpFv+TfOKeBwwUYTT4s=,tag:gEFg60IEN9lb2P2TgiKtGA==,type:comment]
    #ENC[AES256_GCM,data:PcNPJOTG+zK47AZ/82oIVKY+47z9xZs13ywbaoR/6nhh8oKNw8lK4rR/W6rcbyoPAF2MCmO8XdbdyzUBwsujLlxg0qk=,iv:hylU1AvKd8EzNTWqg+6HegWykXqHdeeWdJRKUxwv7N8=,tag:cfSd8ESptVakmVNRd7fAWQ==,type:comment]
    #ENC[AES256_GCM,data:XIwu09dW2dLRwl76pKrnK1SAvMU0GeClYO2saauZiKHSLDE3bedbkUoJOQ4471lLSepyTmhxJLpLdg6rY5uvQunevIGN4oe9VR/BV/1DDx20cuU=,iv:yg0R2T/rJvb0ZMuYaqColzENkTUPZrVHhTi8HRFegFg=,tag:KBkkWCpWrsob6LPcrzEFXA==,type:comment]
    initial-root-password: ENC[AES256_GCM,data:qkkt4QMfYfa0Hzm/VDzkyBHJ/i2uw0ArS7ZW1TsoRMuwqVWq/QAyEw==,iv:UNA04lGMaAK6AjYY0rL3qSgDOzpfrwgeT9fOvPK1ag4=,tag:AUnhrCGRk8ob0YUg72TuSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZXFabjF0cWhmZXRQUWQz
            NW1ySytiUUxxaUZ6V0ppaGFFalk4Y2F0WHg0Cnc2ZnFqT3E4MVNNaE9ObnZ3UVFu
            L1VEOW81elh6TGNHcGxMYUticGErTGcKLS0tIFZtT2VFODdSRnpNaHVyMlJwSDlV
            anlaUzhsQlNMVjBVdUo1WElSbzJMbzgK3tGPu9bBJCMw29K5eaK+VXV7Pk4pmq7g
            pEvBrMLeeSYggCYXVpp0lwnxvsYp7c3IIr5LzUKxXr74k7HL4h6w6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T16:07:47Z"
    mac: ENC[AES256_GCM,data:lSKtyGbp6VPfjzNQxv+20jx1LPdotk+gdfOqvueDuqeJu7h9FopIZEZ8/sfFL2AGFZfZOFyRlX7Q3lv3C8u3m6rsiDkprdzO3oM1wV1qi7AD2vZcpJj4ATWyv8UA97XSTXDHSOLr9v3GxXph/HT73whKb2EKTRI0IiKs7Pe5CiI=,iv:0G1TqjKsA3blv4e4beKhGUlzA7m2XFbxA+wb+jKj/m8=,tag:j3CLJbIkkRvsIRqXz+mKgA==,type:str]
    version: 3.13.3
