apiVersion: v1
kind: Secret
metadata:
    name: valkey-peertube-auth
type: Opaque
stringData:
    #ENC[AES256_GCM,data:+fS19ErmUrW9hN+vMzvZugovaZ6HtOnJCo3PJwAtJTe6ruSTMEN24+UjxK19s2PpbWA1vw3lPxobtm1cmkv1gR1lZcPHDVUuyTQ=,iv:dAipug83K0yoU7oMEll3rpYUgVHl3RrzikRALkJvA0M=,tag:lm5j4IoLl2GXndn+6gPs/g==,type:comment]
    #ENC[AES256_GCM,data:3BvspTPOwyZzaBgcXlxawir9/MaPSBHQgTIAm7K7t4/Y1EAJqhShGqFq9f0pB5FNL85ZsuWtPzDKL7jLdCIdp4hYRDUL8vzC,iv:amqoGqu2b0alDBKUAzvtAisTQEQ3Hr42F87E4EEM2aQ=,tag:1MH6BY0X/DI1JVIp9fDhcw==,type:comment]
    default: ENC[AES256_GCM,data:2O1XcRaokbejQqeSBsgQhW1I1819nM3KYn0R/nxzdPGU57x3TrGp7wCE4kIa7YdZ,iv:9RKOxPQ4CWzzQSCZN2OWe59AypPCzTW79CzTM7ObGPg=,tag:JLkMxsk5lbi6b/mbNC7uLQ==,type:str]
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUWhLcXJZZ0hkN3RscW9x
            enE1RS9YMVl5cStxbWxZTFlaSjBDL1B2V0FJCjlXZUpMTHllUHpDRkJRSStVWC9W
            QUtUeGtpQ2xWeFFHbGNwYXpXekticHcKLS0tIDZEVUhQWURRV045MDJTY1Q0cDFr
            aE9qdytSWVpuQitXTUdjeTVaQjgzdVUKZVUdc2roUQMzlSCJDWpEJh4TwWqvUYH8
            kGlrZ4mqqjbPk9y2X7u5e4zEtqyLYXc3K4GZiuR5ZWh8/cBrYilOtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T18:14:13Z"
    mac: ENC[AES256_GCM,data:f08tvPYNa5jQHnrsOGbxPYSNbTNjz2frssF3C0Ab3QCbkkk79pdFFZ8Y8qXVu+rUSWgMaf393VI9GhugyQkwl426B6ThEqzo+/AXqBorm211C6iIMYtrQlhScfeMsaTlGoEZHqhLOs8TUqTtgGuKL6HP9AnwGxXJDXZ7tNzBfdc=,iv:f8gGy1E0fQ5+kRo7wDLtrYGDrGc+slZHet+lxwRw7vE=,tag:5mSqB4AyBim9MslfnCrfqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
