apiVersion: v1
kind: Secret
metadata:
    name: seafile-secret
    namespace: seafile
type: Opaque
stringData:
    JWT_PRIVATE_KEY: ENC[AES256_GCM,data:fsXf70zef4NGvu999kQ8Z9OxaG4rkrIyfsPvQbW92NpEGtYlj8z9+Q==,iv:3sfX7PPE5cuvOjmUim8PNw/RBx3KBlHnX1cVAZz4bz8=,tag:NSboXvLqVEgFDRzD3X1aKw==,type:str]
    SEAFILE_MYSQL_DB_PASSWORD: ENC[AES256_GCM,data:21OcKWsHnP9lHYzX8liu0nIxundzK7OBHV7sMG6GyAbGA/YLz2vbjQ==,iv:LxtXLDGKS6qJi4D6OVihHSj+vDmQBCNH3cogabjL/A8=,tag:q+z8rKfKZ/izOgmlkDgrtw==,type:str]
    INIT_SEAFILE_ADMIN_PASSWORD: ENC[AES256_GCM,data:4whOXX6iBPmRmDELhuOQV/CbLXxst1a7bmpBgUuQ7gXlxhl96IhsfQ==,iv:nXMqNh44l+SKvs+VUPwsgEBBqucJZrknAkFLSpsGhC0=,tag:HharmQA/gPw8sb+jsyTL4Q==,type:str]
    INIT_SEAFILE_MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:1QzFFzIxDdvaBMT+hA+3/QzgB/o3r4+8rbTLh6nds3fvNP+1xOZUPQ==,iv:vqXLXQ+mP/eDPItHk9jauFiClbRFONnfLglEK6Bfv34=,tag:0c7aE8kWaz2lKUq6S6Id7Q==,type:str]
    REDIS_PASSWORD: ""
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwa3crY0UvcG0rMTFrN2o4
            bkk0QTVRakZYU0RtR0NKSUo2T2dxMDloMGtBCjVlRXZCQy9aaittNTZncVJJWlhh
            dVFYTDdUVEN2aitHbng0Ty9PaUFZOW8KLS0tIFMrZnRsR0FFUU41cURVWEtTV0ZK
            NWQ3NVl6VFpIZmZGemFMc01aaE5yUTQKxw/lK/znzgh+GNkd7eIpSbiivEPTLfT0
            GgNBM5vi0WskWTcY+vChPOaDAmXticv4+q/umxASR2IqEOhXJ/QmEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T01:48:21Z"
    mac: ENC[AES256_GCM,data:Zng66RU37H/qSrnc2OXRfKJGlM66OYD1RRaxRtxFRPJ7Om/IWsvjymu1WgdP1vJ0Mgha5vMxXIlK19oea+iJfJZDPmcjH5ykOQUGDGuEMtcoU9lVSWaKWDMoPZhuq3Efusrwrp0qUdV9s/CZ6FuoPXOSfxU92qvYPg4O+VoCh1o=,iv:dvgQ7tZ8Iy2IjzSuQRcaalG2va01/pNJCnHJ1Qaupt4=,tag:56DY970+LQza8kwkDU/Kng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
