# dyff between <(yq . <(helm show values oci://registry.gitlab.com/devopscoop/charts/app --version 0.9.0)) <(yq eval '. * load("values.yaml")' <(helm show values oci://registry.gitlab.com/devopscoop/charts/app --version 0.9.0))
# vim -O <(helm show values oci://registry.gitlab.com/devopscoop/charts/app --version 0.9.0) values.yaml
replicaCount: 1
image:
  repository: ghcr.io/mrtechtroid/hatsmith@sha256
  tag: d68cfea64828558c2907646a954d0b873f82b0c0c9541e7aa05e2e3a6a3d83f4

ingress:
  enabled: false

httpRoute:
  enabled: true
  parentRefs:
  - name: eg
    namespace: envoy-gateway-system
  hostnames:
  - hatsmith.6j0.org
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
