apiVersion: v1
stringData:
    copyparty.conf: ENC[AES256_GCM,data:1GHbpOwQhU6nRW/NP519LEA9GoZwCkkTiINwIJT5yfDTdInWeGsT+bPHzQyCNA/F7WedDTn7ADIn1hZArTCvKU3z6cq0DpIyn0yn3ofirMxJHG/FZ0T/eG70E4MLsYihI71kKwSVr1GbwnWpvIA2EHWmKSRSO8IYRMfiys/xfmIJaKcBbyrUDtPJ3DJjq5EHDZ4VuICHW3zWEAkN5+qfoQgIPZk31bdYFsuLk64LuRdvfDHuef89GUmer+vDHL5jWPSpOv8CxKi9U6CbuHuNgqhyQVFQEjDMHQEFIc7bzZxxDZVXT/4BCUpl1XgtR1b8jCTT0ZWMnvE9iYARjO41qcCXHaDHztSf2/RpoVrH1qJsYzD4a6a+/tF1A7mQ3MEsti8kopD3U7v4q5EkrdYYtw7dpZhkyZmC0h2PzFWhtEMoFYmTtM3qWsoRlFwxu8NM/8aZBZhgti7nhreCnXuUSl6heKz6Vemh++9LvpW1AAY/ZcsCJcK5TiAl/77gUgXL0ZXueb6vca/mCfUsNpMMEgTsNKoRfkB2llY=,iv:sUoctz5MZjni2K5hbHJKfnqi42NhG5x3nZ3rmSBDr80=,tag:OSsks32yNwABMh+DKjMVyQ==,type:str]
kind: Secret
metadata:
    name: copyparty-config
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYmhPaHpYRE5MbFVWNy9x
            aVFHSlkwclFQK2JzQnk0U2RTZnlaL1VIbGg0CjloUXJIc0pBUHpZTmM1SnFVWFRu
            cmVmd0R2U0o5VTFxYkwxNlRnUkdxaVUKLS0tIGdoa2tXKy9mYWFzS3QxTGdkOTVD
            Nlk5Y1N2QnhjS0xsZGZIY0Z0NlJPVWsKpYYRWjAVx8Vw5KLnTZshYHrE25wQ8cGH
            aQf+6gPGvY0P1P5bqnno49lwhVhMopq8rGAA18Sj+hS2bGy3l6Miig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T03:13:41Z"
    mac: ENC[AES256_GCM,data:iSCO571bkKrfCcQsapdVRGKz7dbiN84atEXK7xtsP16YsTXKu1lgeRcbHXaza7f3E+CRZfXUJVe2Hx+apUpeTWBOj8iRDvQ1oKw9cDhnu/vq4yCr+3pOoz9z7jtedhP7voGBN8iyfeYTbgtvEj/B9p6axoeFk9AOVKPwuEniMoA=,iv:CzSxQ+DTmVJng5ezLYKejCqqJ4uo8aPKd3ek4sJoHp8=,tag:9jexqZCIVNhcp4kfU8U+hA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
