apiVersion: v1
stringData:
    copyparty.conf: ENC[AES256_GCM,data:c1yvAacm0Tut0K91oVQQGk0FU2rg57ulizZPccJcD+QDp6zfBh9vMVJip3uO+3NY23lVjw2Avc0bQ5bp7P8T+Tu/TUtO2i2Jr1RxfNZD89nOqq99XaGVlt9f3cqeAoOYdyObHv6e5JF8oklE9L/XmJ3BTfc4PSs2lJ3FJiGJVF4AeqLU1ZHhGH7XO0u7bRJAFbt7Mo4fWaqDQbS2H0SAVilyL6tnSfltWaoGxFUHFKfQ+G0yVWMz148yBYhOsHChCRdqiUmYCON5A/8LFmgyvRk7aJxjy0OPuMOk9WBkkjY76Yv1jzm+quuAH7A6ZMxImAqgaFxM1xAPpXGIpRSt4VijEL6smRr0g/8JxVnUSGpXdjPB7/gH0U9DYuEkP0AvdO9Mt2sq9n2JOBCQ0FVKU4Sh/QY/of7rtT/5SBTj8Nr2rSSo3xuK9dEhas1dBC7evviQukpNGoNABKkpmyS2u8hv2SlAZa9tqXJevneHkGX60HC7gyFHff/d2vtaF1366Gy60yZZzWATIoXRGpEltQSlBVOnZTdc0ZTj1+QjnyCecmNIJA0wrIa9rPRbIa2gMhw2e1et9f5R51uVhKuchDmoOwDbU8wI7+UQR9GKQ6gBDsJoVCNysVKX0F3ufxpYpLkHS9YFpUNM93XccNL7AHhw+dovdkn+7POtpD7LV8DoPhVmob9zii6sfq9UYz+V9/qZUDGBD2KBD+YIVOtVNojTQ7YFIHj583P+6OkLju/M3sABw9Tkvh9F+s3FCi0df2/Joa/361XaPoIyQePFND9MeQN8l9tVdzGYxId5psBiDwCL5kYMbHfTdTSteeWy312SNTnDan+dDXQb276iYBRG5DY14jtc4ns/BdHkmVDn9VfSF94A2CCpNOCyZThMW7N905wVq7hkHgPW08q0HGk4jphOsL7qkZnUL/xnXp5P8HQoWosLvr725426tVVemGWk4awFHGK+6vA74ipHp2p3U7urcMqg9hGtZqikDrde95crxK7TTgvXKqUH5LUx+8I6Bk5RsemLrHv1UlKYQh4EfLzi+B13Th79BNZpcyXp/EitgXpJIk2PNCI1L7/6h2vJdBWDoPY=,iv:RnrbW2pnYvCb02mKHGI37y8ZJ1FuTbUiWuwJ2OIaboA=,tag:WFTU5xdj6gfqBWpDxBqcyg==,type:str]
kind: Secret
metadata:
    name: copyparty-config
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L0h0VFkrRm5hNE1uOEd0
            dDByTGlBUGZnZndQZzU3Q21Bc0piczRnWUIwClZ3MG9uRHVmMEJYK1BjRTNnelFX
            M1BONWp6ajlZUkxWT1JjYktBb21wME0KLS0tIDU1UUNHSkdkclp0MFRLdldGb1E0
            aEl6SVd2M09US3VsK0M0VzZWT2pGU2cKkz8aVYTBcMLceDDhTphJJ6oJs1SWxUOe
            aed+bFJtNHiDTZn9WvtQwmGLRQnksAXu1D9H7/40V5/8aXviv/a61g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T17:04:06Z"
    mac: ENC[AES256_GCM,data:qgD/Mhs+MJbAmKV5tQziEw6dPCeVa69rb0eVzBUaQPvxqeCBF/eFbpmtyjTv4VyQ11iDF43tHtvT5ERL44vxh7qSMiiiZHhqznjxYW+S3NaeW1aJa7ym6Y4RXtHSvkvZFMFj1o5DfWmiuubitVKiwxJjBDXREj1sVug7HJCe9HU=,iv:N9MAMr/yOAIrPwuI3rG+GpgjjGY8igpin5GAXn0wUfY=,tag:fys9BahvHi06FIfIS+TWKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
