apiVersion: v1
stringData:
    copyparty.conf: ENC[AES256_GCM,data:B1aDob/Ssq7kD8f1aoUHclCSL0C1PCmCSRCkDmpooE7oJINqw77FW12IsgqtW/rs4dhx2fG+vuYQ2ejnXwVK/gwaiT1Jyd+3OD8dWgJ+AbSZJgXlmVbsN+pnLFdj86R9Au/xbAoLyFMrCu9qsJ1qERsU1Mzgq5GpR5AZdwJTEwspyAGMvX0Go3P+w0h3t31YFbK/MXSiOi6NMbsucLhk0kldppzcbN1/rAGLGn6c4oSt6+3Mm1Zt789Obi218CMfhDxdAWYEIg9A2MLOrBkppSa2TJjpD6absPMPE6vxla1AF8WkLoz5dNd6uHfkFPg9LRnFGPVhpdkZr4yRNlOPn2YLiG61IEDyUMELRIiC9DZFGlMF+I7stFA5oyZRERuyM86+IEomqRf1l9KtWSaw7aTljm0mHqkcnsaxpFFub2ehBV+ySfii9nr6FeQLcDPnyLfh2QoGFqQpoOvkPKLYcB3JzwEKa5bbpfVKplzO09t2TWdXBxhYab72hhSdyqUAeWwk6TJTH1Fj1ebsVWZsVo/0Y6uyjg==,iv:AvRLRwhoJFhQYJ5oe1wXDEVSvm9dicaEU7bFn7vxhtA=,tag:0Kkp9joSj32W/MONZ37y6g==,type:str]
kind: Secret
metadata:
    name: copyparty-config
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bWFUU2JxYU04Qy8xV1hC
            WDdORFR2TWZ4bGFGRE9xTTJLMlVRekoxRXk0CmhNZjc0RU1SRmpRUndGYkhNaGRF
            d0EvVUprTEJYamVKSWJmM056NlBxWVkKLS0tIGpLQXpoQ2pZS1lpbGN6RDVMYkVy
            NGx2SlhjSm00bFJ5Ym85RlRFV0dVZFEKDltaS2AimXpLVC7tgOvtyEJLTnVrBNw2
            rUh9pK4qbcmPnKDKJaXNggkC36O8zbj/OQFUguKMR1NrCFzajlcgiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T03:08:56Z"
    mac: ENC[AES256_GCM,data:y0riiFLoT/5xwmipJ3DByk9OrmvByTCbaDN+AZLT1L5dSF/kCoHdZ9QXI+aZRJW0/tsgsNc7AO7G44R4K74N8B5e1Mi6gv4bdDRtEdZTn3Bi4XOKYXejsiNIftbT5uFaavqdhZeYYGQfQB6FutrGqU9dZhYiv5pwdYaAxGhAB5o=,iv:AWiRfWWBhtg5PulnaGMPE3ipYdZ+b0dgmZOciqNkdBU=,tag:d7CkRthTgfRDUcm45ReGtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
