# https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize
# https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-secret-generated-with-kustomize-and-sops

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: copyparty

resources:
  - namespace.yaml
  - ocirepo.yaml
  - copyparty.secrets.yaml
  - release.yaml
configMapGenerator:
  - name: copyparty-values
    files:
      - values.yaml=values.yaml
secretGenerator:
  - name: copyparty-secrets
    files:
      - values.yaml=helm_secrets.yaml
configurations:
  - kustomizeconfig.yaml
