workloadType: "StatefulSet"

statefulSet:
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi

replicaCount: 1

image:
  repository: copyparty/ac
  tag: 1.20.14

service:
  port: 3923

httpRoute:
  enabled: true
  parentRefs:
  - name: eg
    namespace: envoy-gateway-system
  hostnames:
  - copyparty.6j0.org
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /

args:
  - -c
  - /etc/copyparty/copyparty.conf

initContainers:
  - name: init-dirs
    image: busybox
    command: ["sh", "-c", "mkdir -p /data/evans /data/andrea /data/corbin /data/rhys"]
    volumeMounts:
      - name: data
        mountPath: /data
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000

podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true

volumes:
  - name: data
  - name: copyparty-config
    secret:
      secretName: copyparty-config
volumeMounts:
  - name: data
    mountPath: "/data"
  - name: copyparty-config
    mountPath: "/etc/copyparty"
    readOnly: true

startupProbe:
  httpGet:
    path: /
    port: http
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

resources: {}
