NC_DOMAIN: nextcloud.6j0.org
TIMEZONE: America/Los_Angeles
APACHE_PORT: 8443
STORAGE_CLASS: longhorn-crypto-global
STORAGE_CLASS_DATA: longhorn-crypto-rwx
NAMESPACE: nextcloud-aio
NAMESPACE_DISABLED: "yes"
DATABASE_STORAGE_SIZE: 10Gi
NEXTCLOUD_STORAGE_SIZE: 10Gi
NEXTCLOUD_DATA_STORAGE_SIZE: 50Gi
