apiVersion: v1
kind: Secret
metadata:
    name: porkbun-secret
    namespace: external-dns
type: Opaque
stringData:
    PORKBUN_API_KEY: ENC[AES256_GCM,data:iwXVsarhrIxmph0z7cMexR+Az51TJ3Nhr8WBqiW+awhHdPVLITidZu/9dRT8AasE5L0K0EbYG4/UPMQllzNGFQh5yJk=,iv:mG2JzQBCmX0sEzg2wwWQxw7ydN7FCqkHFkyvoYaEKhs=,tag:bvU22xFEX8ZoXK5j8STAyQ==,type:str]
    PORKBUN_SECRET_API_KEY: ENC[AES256_GCM,data:g/+yaK0z+C6YZlIV1k0x2Aj/BK11xBsImC6VytbpAZaYENtcljjkaikXUSVu27MQayw5oiHOQkxoZxC3fHZzOczAgJs=,iv:IbzZ009QVr7gjEMWIuPnepYQEJIr9itgUCMsURkL/QY=,tag:vEiiAur6fUMxFjK2sW4M/g==,type:str]
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwY3RmcUtZQzMvekJqTGhk
            MEdjU1BFajNzSVBLU3hYVDZqbGEwbVBLeXk0ClNMRjlPSG9FcDUvb1VNNCtTV2hC
            SXhGcDdaSlZkRVJ5VWE2UzByWXo1bmsKLS0tIFpSSG1oa1EzUGRicUk2QmdoejNK
            LzhuSWluWEsxeXc0RGhVdG4wWERDY2sKXtrdLjmut9uXxLjFdoCilWuNkj1S3ush
            nG3O3rX3mVqJpdAlTQ4jSAJ7I9+HHCwWW1P1uzqQwj4t9E+RCyc4yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T02:11:14Z"
    mac: ENC[AES256_GCM,data:8dC9YqIJ7CZCW5WI0sU73yiB97k+OHa28FM/S+Pxt+4em23SG2H3FfOBekRKKBN2lKrzrk663oQg/3moDS8bUTXBoqXvuqe/sjacVIf55eB5iC7vFFCzBq+CiCNusgUbh53XnhyGZVrEdjVpqfzy8o3yrXKhMHRhsdSt1anzGD0=,iv:Tj+rieFtq7q5yzBWG4FgOfNtvgZcUpX3jovCroKeQfI=,tag:UU4V8QuYWXUwZuWC4zUGTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
