replicaCount: 2
image:
  repository: ghcr.io/ycdihealth/website
  tag: sha-81828ec7061852aae77a58c1b848f086e4434403
service:
  port: 5000
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: youcandoithealth.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: youcandoithealth-tls
      hosts:
        - youcandoithealth.com

# -- Expose the service via gateVway-api HTTPRoute
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
httpRoute:
  # HTTPRoute enabled.
  enabled: false
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
  - name: gateway
    sectionName: http
    # namespace: default
  # Hostnames matching HTTP header.
  hostnames:
  - chart-example.local
  # List of rules and filters applied.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


# Environment variables
# WARNING: never commit cleartext secrets to git! If you use `envSecret:` or `secrets:` below, it should be in a SOPS-encrypted file.
# NOTE: These have to be strings. Even numbers have to be strings!
#
# Recommended:
#   - Use envConfigMap: to automatically create a ConfigMap and add envFrom to the Deployment for cleartext env vars.
#   - Use envSecret: to automatically create a Secret and add envFrom to the Deployment for secrets.
#   - Use envConfigMapName to specify an external ConfigMap.
#   - Use envSecretName to specify an external Secret.
# Alternative:
#   - Use env: directly to override the env: section of the Deployment.
# Deprecated:
#   - Use secrets: to automatically create a Secret and add each env var with valueFrom to the env: section of the Deployment.
#
# envConfigMap:
#   COOL_MEME: "Six Seven"
#   HOG_RIDERS: "2"
# envSecret:
#   LUGGAGE_COMBINATION: "12345"
# envConfigMapName: custom-env
# envSecretName: custom-env
# env:
#   - name: SCARIEST_NUMBER
#     value: "7"
#   - name: AWS_ACCESS_KEY_ID
#     value: "AKIAIOSFODNN7EXAMPLE"
#   - name: DB_USERNAME
#     valueFrom:
#       configMapKeyRef:
#         name: my-configmap
#         key: db-username
#   - name: DB_PASSWORD
#     valueFrom:
#       secretKeyRef:
#         name: postgres
#         key: db-password
# secrets:
#   ADMIN_TOKEN: kjhfkjgahsdug
#   PASSWORD: kfj09u039jh
#   AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
