# dyff between <(yq . <(helm show values oci://registry.gitlab.com/devopscoop/charts/app --version 0.8.1)) <(yq eval '. * load("values.yaml")' <(helm show values oci://registry.gitlab.com/devopscoop/charts/app --version 0.8.1))
# vim -O <(helm show values oci://registry.gitlab.com/devopscoop/charts/app --version 0.8.1) values.yaml
replicaCount: 2
image:
  repository: ghcr.io/ycdihealth/website
  tag: dev-3ba8e63-1777492822 # {"$imagepolicy": "flux-system:youcandoithealth:tag"}
service:
  port: 5000
httpRoute:
  enabled: true
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - youcandoithealth.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
