---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: youcandoithealth
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: ^dev-[a-f0-9]+-(?P<ts>[0-9]+)
  imageRepositoryRef:
    name: youcandoithealth
    namespace: flux-system
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: seafile
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: ^dev-[a-f0-9]+-(?P<ts>[0-9]+)
  imageRepositoryRef:
    name: seafile
    namespace: flux-system
  policy:
    numerical:
      order: asc
