---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: youcandoithealth
  namespace: flux-system
spec:
  image: ghcr.io/ycdihealth/website
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: chorechart
  namespace: flux-system
spec:
  image: ghcr.io/andreajtucker/chorechart
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: timetracker
  namespace: flux-system
spec:
  image: ghcr.io/andreajtucker/timetracker
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: seafile
  namespace: flux-system
spec:
  image: ghcr.io/devopscoop/seafile
  interval: 1m0s
  secretRef:
    name: sa-github-api
