---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - cert-manager-custom-resources.yaml
  - cert-manager.yaml
  # - external-dns.yaml
  - imagepolicies.yaml
  - imagerepositories.yaml
  - imageupdateautomation.yaml
  - ingress-nginx.yaml
  - sops-age.secrets.yaml
  - external-snapshotter.yaml
  - metallb.yaml
  - metallb-custom-resources.yaml
  - longhorn.yaml
  - immich.yaml
  - cnpg.yaml
  # - metrics-server.yaml # Broken, see TODO in metrics-server dir.

  - youcandoithealth.yaml
  - descheduler.yaml
  - kube-prometheus-stack.yaml
  # TODO: Needs S3 object storage
  # - loki.yaml

  - eg.yaml
  - eg-custom-resources.yaml
  # - garage.yaml
  - hatsmith.yaml
  # - radicale.yaml
  # - copyparty.yaml
  - nextcloud-aio.yaml
  # - chorechart.yaml
  - timetracker.yaml
  # - oxicloud.yaml

  #  seafile ValueError: Invalid CACHE_PROVIDER: database
  # - seafile.yaml
  # - seafile-mariadb.yaml

patchesStrategicMerge:
  - flux-resources-patch.yaml
