---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - cert-manager-custom-resources.yaml
  - cert-manager.yaml
  # Removing this until I can find a sufficiently self-sovereign, free DNS provider.
  # - external-dns.yaml
  - imagepolicies.yaml
  - imagerepositories.yaml
  - imageupdateautomation.yaml
  - ingress-nginx.yaml
  - sops-age.secrets.yaml
  - metallb.yaml
  - metallb-custom-resources.yaml
  - longhorn.yaml
  - immich.yaml
  - cnpg.yaml
  # - metrics-server.yaml # Broken, see TODO in metrics-server dir.

  - youcandoithealth.yaml

  - cnpg-cluster-nextcloud.yaml
  - valkey-nextcloud.yaml
  - nextcloud.yaml
  - harp-nextcloud.yaml

  - descheduler.yaml
  - kube-prometheus-stack.yaml
  # TODO: Needs S3 object storage
  # - loki.yaml

  - eg.yaml
  - eg-custom-resources.yaml
  - garage.yaml
  - hatsmith.yaml
patchesStrategicMerge:
  - flux-resources-patch.yaml
