apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seafile

resources:
  - namespace.yaml
  - ocirepo.yaml
  - release.yaml
configMapGenerator:
  - name: seafile-mariadb-values
    files:
      - values.yaml=values.yaml
secretGenerator:
  - name: seafile-mariadb-secrets
    files:
      - values.yaml=helm_secrets.yaml
configurations:
  - kustomizeconfig.yaml
