# dyff between <(yq . <(helm show values oci://registry-1.docker.io/bitnamicharts/mariadb --version 27.3.0)) <(yq eval '. * load("values.yaml")' <(helm show values oci://registry-1.docker.io/bitnamicharts/mariadb --version 27.3.0))
# vim -O <(helm show values oci://registry-1.docker.io/bitnamicharts/mariadb --version 27.3.0) values.yaml
fullnameOverride: "mariadb"

auth:
  database: seafile
  username: seafile

primary:
  persistence:
    storageClass: longhorn-crypto-global
    size: 10Gi
