apiVersion: v1
data:
  config.toml: |
    # Upstream reference: config/config.example.toml in
    # https://github.com/lowercasename/gathio
    # Any string value here can reference an environment variable with
    # ${GATHIO_VARIABLE_NAME} syntax. Only GATHIO_-prefixed vars are supported.

    [general]
    domain = "gathio.6j0.org"
    email = "b41jplz8@anonaddy.me"
    delete_after_days = 0
    show_public_event_list = true
    # TODO: Setup mail_service
    # mail_service = "none"

    [database]
    mongodb_url = "${GATHIO_MONGODB_URL}"
kind: ConfigMap
metadata:
  name: config
