# dyff between <(yq . <(helm show values metrics-server/metrics-server --version v3.14.0)) <(yq eval '. * load("values.yaml")' <(helm show values metrics-server/metrics-server --version v3.14.0))
# vim -O <(helm show values metrics-server/metrics-server --version v3.14.0) values.yaml
