apiVersion: v1
kind: Secret
metadata:
    name: radicle-mirror-ssh
type: Opaque
stringData:
    #ENC[AES256_GCM,data:BcVVzyId0IW9N8fAe3O/dFPByD9wizWyGRoT59fjpy29Bu4bpmB8M3RZRqlLJi9WMb5fLFiQGAcWATFJwyhav3jApWmh,iv:t+SqcmHdlhX7vuQcPtnxvHK4msLURaZUuTlOZrJrZs8=,tag:7fvmiyNMnX2Vp8NeKzPw1w==,type:comment]
    #ENC[AES256_GCM,data:kI2gXOuGaxH5uKdBdIc7ucQ9U4NNhhjpS0iOMRmEFpnoEzsk6FfmwwqG0Hc29l9gTtGbv3fmdKUjByv5JRzeILQ1IRW/UQ==,iv:Ddx5NSVeaaaalPw+DnfWL1Qvr5CVGc9DUsiwEXWYdTs=,tag:UXEGJuCZO5065B8x6pcCow==,type:comment]
    #ENC[AES256_GCM,data:L02UBnkUQCBiyk2F50ESC1pw4+/uZOI5LfYNcQndyeRy35NVBoBKbcEIJrR2xbjZuRE0aGniIdqftn44hoc4bJhKhRvQJ3hnxQo=,iv:wb8jNjvurTprqqcojAJLtrr8istzNax+MvRgmNHq1IE=,tag:hR2kyrf7np3S6FFgil+cVg==,type:comment]
    #ENC[AES256_GCM,data:reKzUb4C7xAOP8pvWFlHZivJAcAGBs3L3IIb2f7OporWQJqD,iv:q9/0CFi+doO+9oWJ/shyccknXYcmPv2TFyeMW8JHaaI=,tag:T/KKZIbLQK3V/2Afxq3ikQ==,type:comment]
    #
    #ENC[AES256_GCM,data:1GVrxBFvAOTFeqUdOeBNbSuVGPkwZA6QW++LJlubI4ubbXO966/988qGA9oazZDZcihXX55Azvien3ZBa6VL,iv:t34EqNg70lszaMlBug5DhxYMFwEr791jJFSJa871c6k=,tag:xe6ho18hvCS9hfmQ1VKn6A==,type:comment]
    #ENC[AES256_GCM,data:7ZtNLcP6jWYHUTGuJAnR6Z3YCAJ/wf/DfP6qBJTjx3SVu5v1JD22AMRqBSP0k7wm7odNezFP7nWKRyoyf4d/fE66gOtGx6ZskTI=,iv:zhc8yRvehSSYRs5FaZ67w9uokLMGX1wMihbyTXrzMz8=,tag:hfqah/nD/Xx3aKDOBiViXQ==,type:comment]
    #ENC[AES256_GCM,data:Lbtzrl197tkURBLZYAIIkhk5KSQWOw==,iv:18OxAGTJoP2Ae4++K5gm5HKJ0XfVXwHTZB4eNpzYAoQ=,tag:+P58j9Z7YrKXAOp5rpWYZA==,type:comment]
    #
    #ENC[AES256_GCM,data:zSPz7qf+T3oSyVWGBkWdDN8Yk5nZUV3GQ8AM/CG5Jj74Kszwis9JS2I+ZRo2p7dy8u494ESIPADv1QRqNqCrQSTlgYlTj0lSu0s=,iv:8SRtt4ixqcaQ62mETb0Wt378WId381gvIFGhQ4+4rWU=,tag:lzvEESwyx8ISyIOGVZABkA==,type:comment]
    #ENC[AES256_GCM,data:mebf9LjllP/E6mI7hLqBbcFi/cpPlf2zEj4M5WuHQLy2K6/m6RV7GXsFH5xqfiynHlDeob5dT7Y0Qw==,iv:cMBg41U6G7e+zWSLYK+sCrGotPCWGT110DpnWPNtSGA=,tag:wiwpmEfFPRUgybNSWVJlGA==,type:comment]
    id_ed25519: ENC[AES256_GCM,data:+67Wvm9gkxI6SXnC9uncKqzNaju3GT03p4iMxYL+ybWGs2GM2/HRS3vrtft8MedM8JsBJGyv27JCKKNBCbCweqoMxfEHn9FwwF+jeMuAl/60,iv:gAVfskA6yK+VQA0dzCedR1c6BK4dc+KfcnkI8kcr8oY=,tag:vDO5ANKvk/yBuLA2vo8/BA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVXI2aGFkalNENjhRdGFH
            OEJxUXNxcytOQUkrVUVKRE10S041ak9RQVNrCkVPV084NHpESUtXSW80QUlJa0hW
            SkxxVTRMQzQ3cTJPME1UNldoZHJvbzQKLS0tIEhZZHVZdWwwZS85clBaVnpEQ3JO
            UFF1aHRYdGI3R1h0aTNqd3lQeGw3eWMKPanCgHlEpU2dVumktu/9I0ruwoApMfmq
            AR37YHhqRz8DuwoUTnULnxNYDJC1tirsT/C03jwdAtrULatvcbPTpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T23:58:30Z"
    mac: ENC[AES256_GCM,data:fKBTVq8tjYAXq9BTSvPrjze7RaHIOt6aHLXRM3QDSkxhtgHgOynmKtvkG7jTQhbYu786Lk2Tne/ql4xjLFvc95xewQixdsTbSeSNlc574DiK1kUAIKouLokjetR8w+6AqheSAV9yOQL/20ZE/8IkyF7WWincCpDJCC46ZCFtjbo=,iv:ftmDlOWW6s7XzB8Ip4q8JgQ5aWf0D/42z3BNyDDCQE8=,tag:TChJStdTdbwB8meYykc92g==,type:str]
    version: 3.13.3
