apiVersion: v1
kind: Secret
metadata:
    name: radicle-node-key
type: Opaque
stringData:
    #ENC[AES256_GCM,data:XZyqabzLBhIP22tIHPnzwrYVel8ZNfXAlZBu8/ryIyrOzQsYo5W1TlAiSebqwkY4PduJJ+DyLIOKPSWKp2w5KhT4WOTnTgaa,iv:JfSibKlHefTmrv+HBWidQN0vY23fw0aiyq8IMnIpkRI=,tag:V5ZtM/3I0xOn2U3vyONmrw==,type:comment]
    #ENC[AES256_GCM,data:g8KCU0+UKbaV/MKRKGQqhD+ea1XcLpbC1c/5YeLzly1+vxP0I3JjE4CtZq3nIHlJgEDmFBp881eGESfPxxxo8tLVrf0MSig=,iv:tIJeeMSA6CXVcU2NU1D58u1q+5W9fS6T0hzQw1uovLA=,tag:x+v2qUmsovQKPvjXUR5ZJg==,type:comment]
    #ENC[AES256_GCM,data:M/4QM6n6M+QmjcVtcoNOO+8c1ogXQk+tWcx+BFk406/FhvlRP2FqeuakE8h/yhiwMu2nzIVDRv3St2ZYrCdUfb2Vu+O7,iv:P5tZYa/q9HnKnhidhMKIWb1B3mcCXJU2kLoudCI+3bs=,tag:hzQOJXX7ZkMpyqaftV3flA==,type:comment]
    #ENC[AES256_GCM,data:CA60InuB/Rb5VkJeIDjuxfMJ9soCa5Pi6Sqe1pSmsKScCr0uftZ33lPYI0pcidjEXXsZ3Q2adv4aJCZo+XqLJcxxfRWH9vIMiivwrw==,iv:ucD6YsC/sbhBleE/2TjDGNMPA1lt+q3Rdme020bqvsE=,tag:Zric4ZoG8jp5Vc9pFmWK8g==,type:comment]
    #ENC[AES256_GCM,data:zTC8IT61/vAlqyMxF5k42Fk=,iv:xDNIWP8h7S9Ifu8gIOetZkO5yhLCGL36+4i4KFT/q24=,tag:8+V4Eao+48GuOl/HqMPyXQ==,type:comment]
    #
    #ENC[AES256_GCM,data:49WodW4g32/mLyA5VkthLzm14doXDdDX2A54jsc2z3TWxt7I1D2YMmbcgqAELeoj/KI0uzWfBm3zmX6VCtPp++1VixG45QSYpnowLAQ=,iv:z7jD03t/+q82dx+oyb6nlwp81fAisWr5vkDQKXJqaco=,tag:aLU0C5wanIjbqxt5UsRAoA==,type:comment]
    #ENC[AES256_GCM,data:LOTZwgnanlhuDFPexzx1W+I3DG8kAAcTyZcrDYtCVMTyUnsbNc+vBUaKPjaQ2JL499CNH5KmbE9mm7ZVpuQlDTMVJ0g6NykR1DJnrg==,iv:c/GQNBrbldZcYuecAT8NqkmdtI82/+NkBXq4ZBin928=,tag:xAiteKdSU3PQ6sd7utqjYg==,type:comment]
    #ENC[AES256_GCM,data:BsASJ8ZHLe82zrHY2tTrKq/fvx4WTrli/hjX/TrQ4DqxClO6wM/mvVcEHtWsoSdCkPAc7GlH1g==,iv:zg42JVIOfedxm9oB9KvAZt6tEDpdRC2vxi3zaPQRf6M=,tag:LimkekjS71F4sxScvvtkNQ==,type:comment]
    #
    #ENC[AES256_GCM,data:AsE58liiT6RnyIf5OxBepZXysmYWN2tqGkmo/LlnqLQYCXZ1Wvdn/X0HiCukprNSDCPUiMLIkVXrBg==,iv:UNTIYI0YhroM7Wxi18FSogN1isS2XhlfFZEVD/FGECE=,tag:CPPZPec+SsGIuaFDq7mFGw==,type:comment]
    #ENC[AES256_GCM,data:RRXLcpjs0Zrs6b9x9JHCZbMX/VZ0+JTF/GVEvaEp7w4XrmAtymL6HHGBPcUcJSFgqi/IJYpJ5XBs7KpI/KnExpYx0/0r/KR87bvZ,iv:02Q87nFDU7TgCLwtFE8NplZdBQOjDi6cUyUgW4Y8HjI=,tag:JAJ04QXgwjdsY+KBGXi6ow==,type:comment]
    #ENC[AES256_GCM,data:6t2dayvdkMpX60unFJNsUh1Kkn5yxsTzoWEMzaY3q1ubKxOpYd9xBO4hvjDF2Kj79TlTGZVFCti5GP8qNZj8OT+8PSBO2Ht6y5NfsQ==,iv:8/p1kpUIdU0tS5jBoRaTelms+q5tFgdCojwe/8uFlYM=,tag:CISVNhv+kfaF59k1Ea0NXg==,type:comment]
    #ENC[AES256_GCM,data:4+8Mx/z49AJQ86ZCtfARbftBs8fqOR62ny9nFjwnQSlquxqbRI/MPmsibuSb1A==,iv:3SMV7c3DKERPTYM4EZ33R3mPUh3rpShsjC47zIBndK4=,tag:eE77drarh1wT3WQPiXTzcA==,type:comment]
    radicle: ENC[AES256_GCM,data:zrcS3JeasMI=,iv:1rTLj6zc75s4p01fbcSO4dTuXP0q4B35XXZtqwTP73k=,tag:0JgOlOfY8TVsum7l7a1HaQ==,type:str]
    #ENC[AES256_GCM,data:LNO9DJo/VzmcQIxkBe8b7/cgnSMS3xkWhyboGl6SqynLyeuFy8wpPNOPW0ltlDdE58dZTx+a6fO9XJO0imTQDnIJ,iv:SSTJsKuiC+gyMCi68faI+YVvgd57zVfDr4SLPEAx9ls=,tag:KanfjJBFfJrcY1zJDhNSow==,type:comment]
    #ENC[AES256_GCM,data:/49dThCUmsBs6X7EoLQBfZ3vWIoNJg7s4tUlzg==,iv:b6B/DHASCv5T6o1k9uvHFciuutTU4wrWOTHr7/KwZmo=,tag:Noxld2y3hjy3KlU/mkJzaw==,type:comment]
    radicle.pub: ENC[AES256_GCM,data:qhunhFX55YQ=,iv:E/wqt1Jn2nqR6KncP910UcVZOb72aZI3EdZR2ZE/Wq4=,tag:e9pS7wCaUyDY2KkDsRlhdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNHFtVmRCSmVUTzNPakN1
            ZXoyeGtTRldteUZscEZ5aDdlOU9NUTNWY1hJCkJEVXFmQVdCRWdMaStaeUw0ekps
            RFNoM3JaanlxZEFhdms2RjVYMHMyUU0KLS0tIDYza2xoS3RIZDUyQ2pEd285SVlp
            cUpsZ3dHeDEzT0phWmd6UDVOQ2tFc0kKl2Yu6+uLEGBnUi2nGPyU+PrDkm9YZyxO
            QUjtdsauaNn3nEKucVgHJg1ZNK9oDq5Y2SRzJIANlWrnifIo4Rh7nQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T01:22:11Z"
    mac: ENC[AES256_GCM,data:Xv+9gxLEDzuB8Y2/L/42akNcoPtX7VQ5vjywXs56GIKvxmGGfg3HYnRcNdGP6VgIzb4Es491QonMSsXt/KPBzfVFGEM91uFMp8brYN1vjCwjAvNtRlp57dVJ8BEt4SLPMAbGCW9Mjt2jZ26aEFJAXrlXdv3cwB+IG0WDiWUzjiE=,iv:+IQ5j7xu4o4yMxVmaBnbhoPWSWQ13owWisokspn+NX0=,tag:1Ipv7gmcdwM8RbTDddjd+g==,type:str]
    version: 3.13.3
