apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-apikey-secret
type: Opaque
stringData:
    apikey: ENC[AES256_GCM,data:dSkV+h/eNF0=,iv:WYaEmi5HpU+KwgNHFDYVCBf4RePk9cPsmxi7agp6C6E=,tag:1RGsrv+ZgbTwLn/vCmsXUg==,type:str]
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUEdsbndsSnd6TkQ3ZEE4
            eVptdzMyNFZwRnlwVFB2L0JwNTFwOXJBM0RFClhzdlZUemY5WTArdC9NSkwrRFVh
            cHZwaFlqTVBja1h3YXFBbmQxeXF1VFEKLS0tIGhUVkxiOTczcHdZcXdFWmszcmU1
            eDlCRmpkaWVzd1VUL2FlSGxtSHZjeXMKqdKIotulioHxJ+c4WigZF81CBSCaczrE
            F/LKMr5SsO7IJIkVAJIioFBEUVMU1KYAmzytP/LJkgLNfGfwYYljvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T03:19:49Z"
    mac: ENC[AES256_GCM,data:MacbihIdZYZ68m+FZRlQr8GldaUGkR8a9LQ1BK7XQJohyje6T1Telai4V/bZS6ZLdD4as4mmKfeVwax0oQrX9nk2nuTSagsHJ2OXct6bndGt/IdikNVgalTQsuW7GOfN6fx3GUMlSwdyT08XMn5RGyb+ceOEI6YXLMPM2qTSqdI=,iv:ySrROjPnUDWSHMTcTp0VkN/bqJuGJFARmuKLIRe/P7A=,tag:pu/3pmjLpv+0YQmTX3eFuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
