apiVersion: v1
kind: Secret
metadata:
    name: porkbun-secret
    namespace: cert-manager
type: Opaque
stringData:
    PORKBUN_API_KEY: ENC[AES256_GCM,data:t86/B/HBREApJfReQruvDVgbC0a6s4Kj9KQ6SizippChhn6e1PM0GdbnA/LWQJXQGypboLT4TIsfsBrL9YbHshUzP9s=,iv:OFkIwJUgCUw/6e67VcCAIy2iKJ2+SjYqyzwRNwBMvug=,tag:bdp0tZRWvwUXRWf6SGIw0w==,type:str]
    PORKBUN_SECRET_API_KEY: ENC[AES256_GCM,data:+ZOw0yhiOgujiANOoHVVpGJdqmZ1tfqC+mutfXNDyxEEqTGXnlGqGWHhTKeVzZ7feZAXm4JMs1ZcGcrYukkPZJ2CPD8=,iv:8xnmYTs7Ix4ywSr9AJdNT6G0t8qbywDLOh6UUluR5Yo=,tag:IzIcAsnV2pFOC02P8uk5+Q==,type:str]
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWY1krOWF3R1A1bVdwVTd4
            bjRHTk11VkRST3o0bW5XMnRORjF3UG0raUNRCkRvOHBqOHNsVVVMamhISERWWVVS
            VlVmNGkzN2J4YlVKc01YdWFCVHAybDAKLS0tIHNYaFVLVC9IcUx5Qk5RWC9hM1lj
            MDRWbGxPUnZZU3c4ay9YSTBtYTQrbWcK/z5fIio5yyIpTK2XIHzW1Qe32zVzVCAO
            n1Cxl6+DbCcFP0y+DJ+jIog1FO0e4AB298pXkg+i3Alcke1yN/RJrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T02:10:21Z"
    mac: ENC[AES256_GCM,data:6JIph513VwIN61DBFxvcj9nECalIfSQ+JzpPHpG5x6u5xHPLBXWnl9ScZRpXyb3Av/DeiNplRW568M1x/UpUpTNvOgfPT8/ZIGmkO6gSc1EcFqAplrHdyxCeEYX7DnD8QyetKyeewyOaj1Wj3HVynsVlhBBndZasN7LZDMq6cjw=,iv:vdSHqGk9w2iQ/O04ABkfAPPV/LyOwmXbsFHTxPYnUhM=,tag:2Ajh/DBuU0TuiPsT2ApPnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
