garage:
  # Setting this to 1, because we're already running on a bare-metal cluster with Longhorn with a replication factor of 3
  replicationFactor: "1"
  s3:
    api:
      rootDomain: ".s3.garage.6j0.org"
    web:
      rootDomain: ".web.garage.6j0.org"
persistence:
  meta:
    size: 10000Mi
  data:
    size: 10000Mi

deployment:
  # Setting this to minimum needed for high availability
  replicaCount: 2

ingress:
  s3:
    api:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: "s3.garage.6j0.org"
          paths:
            - path: /
              pathType: Prefix
        - host: "*.s3.garage.6j0.org"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: s3-garage-cluster-tls
          hosts:
            - s3.garage.6j0.org
            - "*.s3.garage.6j0.org"
    web:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/tls-acme: "true"
      hosts:
       - host: "*.web.garage.6j0.org"
         paths:
           - path: /
             pathType: Prefix
      tls:
        - secretName: web-garage-cluster-tls
          hosts:
            - "*.web.garage.6j0.org"

resources: {}
  # The following are indicative for a small-size deployment, for anything serious double them.
  # limits:
  #   cpu: 100m
  #   memory: 1024Mi
  # requests:
  #   cpu: 100m
  #   memory: 512Mi

monitoring:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
