apiVersion: v1
kind: Secret
metadata:
    name: harp-nextcloud-secret
    namespace: nextcloud
    labels:
        app.kubernetes.io/name: harp
        app.kubernetes.io/instance: harp-nextcloud
type: Opaque
stringData:
    shared-key: ENC[AES256_GCM,data:W5y8p0mgelb5GSBYwdyPe1AJMWpCUA==,iv:ektjCwwB8E8j2spCBtExN+iT7OmTEMypRfMl43ZFGV0=,tag:cKVYlUFET15b/kjbgVSDYw==,type:str]
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMGpjeHAyWmNaUWtmTlB1
            YnhFTkJ1T202ZE5BdFhOdXRJVGdBZy9KK1NvCndHRmlCMlZnWnVQRzBreHFxQjFt
            Umlyc05TdjhkTDBUbWp3S2x1U2tiMU0KLS0tIDd2QWhQR0RyOE4vbTd4ZkhGNVc3
            cW42NUN5STg3UkMrbEpScng3NWtYYXMKL9dYd+yptjBYW6e6org3KfmxvFqA7JWC
            g4Y8hvPbANYD87DSkdTmZrM5+dY6kq75CG6MwOxQhir6EXGad8cvWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T04:54:12Z"
    mac: ENC[AES256_GCM,data:DMqruEEmetdv5umCQERQx/WRAsHvsFT5kj2+mcwfHqLBKjT2ddzm+6G92S5DpkgACZsvNMVp80Bb1HTHu852f7xP5s+tleFXzOw4hpu/xawahIoneW4E/NiuRfJ8Ck8GLAU6//2f52RVtw4ZQm3KsBigsDu2u6zTxX470S1FE0o=,iv:ytpbzvfq0uXQlM/nPS3AdL06mDQbXM8iLKS1u2Vr/Do=,tag:6Vy7UOug2MujrhpflB3/Yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
