apiVersion: v1
kind: Secret
metadata:
    name: harp-nextcloud-secret
    namespace: nextcloud
    labels:
        app.kubernetes.io/name: harp
        app.kubernetes.io/instance: harp-nextcloud
type: Opaque
stringData:
    shared-key: ENC[AES256_GCM,data:uP0dFPjRPFoqMBKbJKQAlrH+3lB0E/tXeU9NTgVXgR6HAA==,iv:FkV/isFizxUdscKTwDnAT+XYYg/aKdNKqBDuWTBEuYA=,tag:OcOU/USMrAirj3ECMkdiLA==,type:str]
sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMGpjeHAyWmNaUWtmTlB1
            YnhFTkJ1T202ZE5BdFhOdXRJVGdBZy9KK1NvCndHRmlCMlZnWnVQRzBreHFxQjFt
            Umlyc05TdjhkTDBUbWp3S2x1U2tiMU0KLS0tIDd2QWhQR0RyOE4vbTd4ZkhGNVc3
            cW42NUN5STg3UkMrbEpScng3NWtYYXMKL9dYd+yptjBYW6e6org3KfmxvFqA7JWC
            g4Y8hvPbANYD87DSkdTmZrM5+dY6kq75CG6MwOxQhir6EXGad8cvWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T05:01:59Z"
    mac: ENC[AES256_GCM,data:Ys+C+SaUltPHFD+rXO6qLed9uqPQYJM7oYUHOtHELW6SEXg7sDSxYRzmRyS22CFHtmjF8Ek33F7uwQTiCwm1IkY8CmvFUiH33iBy8MDyT+vSUXn26hqw34i/1YZ1uWAUxH8XCsojTEU23DzwB/0xuJ6xLnb8Oo0ogsBv8N+n+aU=,iv:uu00VfMUgsYwfvNYSe3UX0jlrgJmqJEioYcAxbiGCkE=,tag:q7fgBKdlsOQRfbbuJz+XMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
