apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - sa-token-secret.yaml
  - harp-secret.secrets.yaml
  - deployment.yaml
  - service.yaml
