apiVersion: v1
kind: Secret
metadata:
  name: harp-nextcloud-sa-token
  namespace: nextcloud
  annotations:
    kubernetes.io/service-account.name: harp-nextcloud
  labels:
    app.kubernetes.io/name: harp
    app.kubernetes.io/instance: harp-nextcloud
type: kubernetes.io/service-account-token
