apiVersion: v1
kind: Service
metadata:
  name: harp-nextcloud
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: harp
    app.kubernetes.io/instance: harp-nextcloud
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: harp
    app.kubernetes.io/instance: harp-nextcloud
  ports:
    - name: http
      port: 8780
      targetPort: http
      protocol: TCP
    - name: frp
      port: 8782
      targetPort: frp
      protocol: TCP
