apiVersion: v1
data:
    .htpasswd: ENC[AES256_GCM,data:HeTdhDTol/E/uI+7st3g6CQewRzYCAV13aCNvO/mGo/Vf0+Zl2RXPgiX8ZwagR7oJVSpmA==,iv:SPi9MDKv2c6yCkCVMAsoKxAFtVvtKAdoxk7YvEx4VDw=,tag:ZpyI3Z9TF0EFNcC0+PnIeQ==,type:str]
kind: Secret
metadata:
    name: basic-auth
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWW1sNEhEV1k2UWFsWXNN
            c2VzZDZoYkIyMWlpS2pzcThyTldBMHNXYkJZCnJyWWxCbTZMbyt5NFBuRTVMdHRC
            MWtFWkIwWDhpM1VzTExqUlNvYk1pcDAKLS0tIDBSd2pNNDBnbkJsTFlSVklrQXNw
            ZTZUeEtxWmZrazNWa1pmYWdDVmJFUzgKhcFh/pMLdp3ZkYQLf0IMvUFeUac3u3Zb
            Q3p0JOf+jo/hyEHahKRZz9oghrjXnAEO5WMMgsmsjhSfrdCvrWPMWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T19:31:15Z"
    mac: ENC[AES256_GCM,data:zdE2sKhJu+ImOg1gQHqmLkoGnmbXiyIdEiDQ+Af/XjCT6NwDDlFQiMFMA4P3idzlKVIHcGmO1FqCIH3U2BS1+ydC1GvQe4vzwyW4R9gTTUPhLf0mbfmSlyYTUbZHJ6mTlW8Rdx494wbaC7kw6hMeTdcYVShM6fPZLG4WORU5wUQ=,iv:sNERCYjHJgFDfJ1Q09cQ3eQc9GHZvBmCubvc+GvsjFI=,tag:XDlBVqJe+UyGE/bmbwQBQw==,type:str]
    version: 3.13.1
