apiVersion: v1
data:
    .htpasswd: ENC[AES256_GCM,data:YYpzAr30ICJjR8RhQw4fZIIfy/AAizrjdVJlx7Uqgg5JMX0MmaKS5CrRu7EXjPUphx5HTqNeKk6Y4PjTFk76wR/TAKSpMlyOBP74AjMw7G0IJThw3NWXDA==,iv:KP+1i0mvxJ3QOOAWVmY8JfG1AA9gfTXRee0TbCAylro=,tag:HYGhONPU4IEqp7xBlSh3Fw==,type:str]
kind: Secret
metadata:
    name: basic-auth
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dFJFMmlxUHNiSnkxL1RL
            Z3UrKzZ3OGYwdXdjT0RqRURNOU82UDlaRVd3CjJrS1ZyMXFZUk54bUs2TXVKWkRH
            L29BY1FhNE9TWjUzVExiMmJmdmF6Z0EKLS0tIFZGcWVHRHRKL0xLMzZoTHQxcEFE
            OGFpK2ptR01xODYzRHBXWXVuaWMweG8KgT1ejWjZZSjoMJXM8LhsLS2WfDaBqPql
            hNSXaOtrJysDoIPmAruHiaUuT+twmOCbNnSMecd4l2w/XfpvcVBBLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T18:27:19Z"
    mac: ENC[AES256_GCM,data:f4C/opNbwZLBJgrjxNJqgQOPljpjcHt2mwe4re70etewxa4ke+W5dpYFlRXwb69PxY+1tEP0NUCsXUKfg4AXflWPxvg5fPUJzIyooq+WAvJ6/vsFze7L2X0tXUBs9v9CVk6VeCdnAociA8i+9geDk/UgB/jUX8z8fMd/YCyCy4A=,iv:EOZdHV/tD1DRalla3S48roTG9KZaoS82XCS7zHAUa+c=,tag:pLOk/NbdMgjjVbcv/wCvKg==,type:str]
    version: 3.13.1
