# dyff between <(yq . <(helm show values oci://registry.gitlab.com/devopscoop/charts/app --version 0.9.0)) <(yq eval '. * load("values.yaml")' <(helm show values oci://registry.gitlab.com/devopscoop/charts/app --version 0.9.0))
# vim -O <(helm show values oci://registry.gitlab.com/devopscoop/charts/app --version 0.9.0) values.yaml
replicaCount: 1
image:
  repository: ghcr.io/andreajtucker/timetracker
  tag: dev-9869f1b-1780178033 # {"$imagepolicy": "flux-system:timetracker:tag"}
service:
  port: 3001
httpRoute:
  enabled: true
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - timetracker.6j0.org
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: timetracker-db-app
        key: uri
