sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOTJSN212b0trWDhySSsz
            di9ZMytTdFBxK3FobEpETmlabkpvNzhINXhZClhZVmtPdkNxbXBHakorOS8xY2FI
            SnJjTktjU2NyNWk0OG5iUFlUVTlLQ2sKLS0tIHQwWEp4ekl2N2ZGZkg0YlhVK2hH
            SDVnd1ZKcVd0VzhBdjJSQUFabml1MmsKTqCxG2u1zSA+LOO50OahCrdQ49GyF6dI
            6tT36nwI/nME/JUc3kAd3HLDYvThwM7fsP4lB411kJQlAwluHJf5iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T03:15:36Z"
    mac: ENC[AES256_GCM,data:iwzWe9FRGxT8psF01ijavX7pyl7TP6JZKVHqnYSwY9a6waEcEhujaAMRClAdt/Ex0Gl4dICB0/2jcnCBuf2NuF4gKImjTSwFk0xn9fNpBz42faLv0HSlZvKOZdSYViZBk+lRqRJoeSbdkJSDGfWtggbcJ8glGASGPHZqzZA2Vsc=,iv:EjhaFYz417xwlUzsadN64QCOFIxGzEUCN32MKmqUweI=,tag:wId/RlyWDCSnd2Dx8a+ifg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
