sops:
    age:
        - recipient: age1hyw8w5vnp0kxrrcdd02f30r3euyszyaxs04qnw8d0jnmf9vuhyuq6qz9k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWEd6S1N1NWYxdGF1MUV5
            eW40WldkWmVnUWhLZU1tU0NpZ0lHRkhTbXhVCllQaTgrUUFWQm1aSVlZa0xnYkxs
            dVZzV0RyLzBsb0RLRTNBaHl0eCtEUEkKLS0tIDNRajJkVUp6Wm9oeUVwQlp3UTRt
            VGJhWVdjRTNvRnNpMWQvRTZBaEk5YXMKd8CO+heATqtpqjud0FsQiBE/zw2Qy/0J
            XOQkVTNS24+a0B9sHsXqpoJbwAk1LYHqFpkB5e3NX5guw/602l3e/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T03:19:49Z"
    mac: ENC[AES256_GCM,data:piSiw3lGh4u7kG/Gb4HpN7TOEigUSn+FI18AevwLOIvwPxrdXJyVARmyCebInd7lYAfxelD8sXA9l9oQWYSI7rm9wdF+xcmTBbasGgrazrYR+u6p4JLHwxopQuuBi17Tl0T4cyrpPe4qzWjv0aK5bcfczvkF6OPdKsSHqHgUiLk=,iv:txLextryukDcb08A/Ql9FRh4zKeQLITqiELsfsvk4qo=,tag:mG5nSAv7NKY4GeRaQtYrUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
